# roles/web_app/tasks/0-wipe.yml
---
- name: Remove Docker container and all related files
  block:
    - name: Stop and remove Docker container
      docker_container:
        name: "your_container_name"
        state: absent

    - name: Remove Docker image
      docker_image:
        name: "your_image_name"
        state: absent

    - name: Remove docker-compose.yml file
      file:
        path: /path/to/docker-compose.yml
        state: absent
  when: web_app_full_wipe
  tags: wipe